more core_devices.h fixes
guarded the warnings with #ifdef ENABLE_DEPRECATED_MICROCHIP_WARNINGS as a prelude to a solution to not trigger them from mTC code.

added a missing = sign

still hitting errors I don't understand in 2.0 (now released, no longer RC):
```
/Users/user/Documents/GitHub/megaTinyCore/megaavr/cores/megatinycore/core_devices.h:1931:30: error: expected unqualified-id before numeric constant
     deprecated_constant_name PORT_INT0_bm = PORT_INT_0_bm;
```